# Generated by Django 5.0.2 on 2024-04-03 08:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 8, 46, 53, 841795, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 8, 46, 53, 842790, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CheckTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finded_question', models.PositiveBigIntegerField(default=0)),
                ('user_passed', models.BooleanField(default=False)),
                ('percentage', models.PositiveBigIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talim.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(help_text='Nam: A ', max_length=1)),
                ('true_answer', models.CharField(help_text='Nam: A ', max_length=1)),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talim.question')),
                ('checktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talim.checktest')),
            ],
        ),
    ]
