# Generated by Django 5.0.2 on 2024-04-06 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talim', '0002_alter_group_end_date_alter_test_end_date_checktest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 7, 40, 50, 665164, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 7, 40, 50, 666163, tzinfo=datetime.timezone.utc)),
        ),
    ]
