# Generated by Django 5.0.2 on 2024-04-21 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talim', '0004_alter_group_end_date_alter_test_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='descr_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='descr_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='descr_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_uz',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 18, 54, 20, 443043, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 18, 54, 20, 445038, tzinfo=datetime.timezone.utc)),
        ),
    ]
