# Generated by Django 5.0.2 on 2024-04-22 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talim', '0005_course_descr_en_course_descr_ru_course_descr_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 6, 25, 18, 593716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 6, 25, 18, 595714, tzinfo=datetime.timezone.utc)),
        ),
    ]
