# Generated by Django 5.0.2 on 2024-04-23 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talim', '0006_new_body_en_new_body_ru_new_body_uz_new_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('img', models.ImageField(default='media/no.jpg', upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('body_uz', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('jobs', models.CharField(max_length=50)),
                ('jobs_uz', models.CharField(max_length=50, null=True)),
                ('jobs_ru', models.CharField(max_length=50, null=True)),
                ('jobs_en', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(default='media/no.jpg', upload_to='testimonial/')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 12, 51, 49, 516852, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 12, 51, 49, 517849, tzinfo=datetime.timezone.utc)),
        ),
    ]
